#############################################################################
# Makefile for building: mdieditor.app/Contents/MacOS/mdieditor
# Generated by qmake (2.01a) (Qt 4.7.3) on: Tue Feb 28 14:25:38 2012
# Project:  mdieditor.pro
# Template: app
# Command: /opt/local/bin/qmake -o Makefile mdieditor.pro
#############################################################################

####### Compiler, tools and options

CC            = $(CCACHE) /usr/bin/gcc-4.2
CXX           = $(CCACHE) /usr/bin/g++-4.2
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.6 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.6 -Wall -W $(DEFINES)
INCPATH       = -I/opt/local/share/qt4/mkspecs/macx-g++ -I. -I. -I. -I/opt/local/include/QtGui -I/opt/local/include/QtCore -I/opt/local/include
LINK          = $(CCACHE) /usr/bin/g++-4.2
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS)   -L/opt/local/lib -lQtGui -lQtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /opt/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.6

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = editor.cpp \
		main.cpp \
		mainwindow.cpp \
		tileview.cpp moc_editor.cpp \
		moc_mainwindow.cpp \
		moc_tileview.cpp \
		qrc_mdieditor.cpp
OBJECTS       = editor.o \
		main.o \
		mainwindow.o \
		tileview.o \
		moc_editor.o \
		moc_mainwindow.o \
		moc_tileview.o \
		qrc_mdieditor.o
DIST          = /opt/local/share/qt4/mkspecs/common/unix.conf \
		/opt/local/share/qt4/mkspecs/common/mac.conf \
		/opt/local/share/qt4/mkspecs/common/mac-g++.conf \
		/opt/local/share/qt4/mkspecs/qconfig.pri \
		/opt/local/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/opt/local/share/qt4/mkspecs/features/qt_functions.prf \
		/opt/local/share/qt4/mkspecs/features/qt_config.prf \
		/opt/local/share/qt4/mkspecs/features/exclusive_builds.prf \
		/opt/local/share/qt4/mkspecs/features/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/release.prf \
		/opt/local/share/qt4/mkspecs/features/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/x86_64.prf \
		/opt/local/share/qt4/mkspecs/features/mac/objective_c.prf \
		/opt/local/share/qt4/mkspecs/features/warn_on.prf \
		/opt/local/share/qt4/mkspecs/features/qt.prf \
		/opt/local/share/qt4/mkspecs/features/unix/thread.prf \
		/opt/local/share/qt4/mkspecs/features/moc.prf \
		/opt/local/share/qt4/mkspecs/features/mac/rez.prf \
		/opt/local/share/qt4/mkspecs/features/mac/sdk.prf \
		/opt/local/share/qt4/mkspecs/features/resources.prf \
		/opt/local/share/qt4/mkspecs/features/uic.prf \
		/opt/local/share/qt4/mkspecs/features/yacc.prf \
		/opt/local/share/qt4/mkspecs/features/lex.prf \
		/opt/local/share/qt4/mkspecs/features/include_source_dir.prf \
		mdieditor.pro
QMAKE_TARGET  = mdieditor
DESTDIR       = 
TARGET        = mdieditor.app/Contents/MacOS/mdieditor

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile mdieditor.app/Contents/PkgInfo mdieditor.app/Contents/Resources/empty.lproj mdieditor.app/Contents/Info.plist mdieditor.app/Contents/Resources/icon.icns $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) mdieditor.app/Contents/MacOS/ || $(MKDIR) mdieditor.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mdieditor.pro  /opt/local/share/qt4/mkspecs/macx-g++/qmake.conf /opt/local/share/qt4/mkspecs/common/unix.conf \
		/opt/local/share/qt4/mkspecs/common/mac.conf \
		/opt/local/share/qt4/mkspecs/common/mac-g++.conf \
		/opt/local/share/qt4/mkspecs/qconfig.pri \
		/opt/local/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/opt/local/share/qt4/mkspecs/features/qt_functions.prf \
		/opt/local/share/qt4/mkspecs/features/qt_config.prf \
		/opt/local/share/qt4/mkspecs/features/exclusive_builds.prf \
		/opt/local/share/qt4/mkspecs/features/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/release.prf \
		/opt/local/share/qt4/mkspecs/features/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/x86_64.prf \
		/opt/local/share/qt4/mkspecs/features/mac/objective_c.prf \
		/opt/local/share/qt4/mkspecs/features/warn_on.prf \
		/opt/local/share/qt4/mkspecs/features/qt.prf \
		/opt/local/share/qt4/mkspecs/features/unix/thread.prf \
		/opt/local/share/qt4/mkspecs/features/moc.prf \
		/opt/local/share/qt4/mkspecs/features/mac/rez.prf \
		/opt/local/share/qt4/mkspecs/features/mac/sdk.prf \
		/opt/local/share/qt4/mkspecs/features/resources.prf \
		/opt/local/share/qt4/mkspecs/features/uic.prf \
		/opt/local/share/qt4/mkspecs/features/yacc.prf \
		/opt/local/share/qt4/mkspecs/features/lex.prf \
		/opt/local/share/qt4/mkspecs/features/include_source_dir.prf \
		/opt/local/lib/libQtGui.prl \
		/opt/local/lib/libQtCore.prl
	$(QMAKE) -o Makefile mdieditor.pro
/opt/local/share/qt4/mkspecs/common/unix.conf:
/opt/local/share/qt4/mkspecs/common/mac.conf:
/opt/local/share/qt4/mkspecs/common/mac-g++.conf:
/opt/local/share/qt4/mkspecs/qconfig.pri:
/opt/local/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/opt/local/share/qt4/mkspecs/features/qt_functions.prf:
/opt/local/share/qt4/mkspecs/features/qt_config.prf:
/opt/local/share/qt4/mkspecs/features/exclusive_builds.prf:
/opt/local/share/qt4/mkspecs/features/default_pre.prf:
/opt/local/share/qt4/mkspecs/features/mac/default_pre.prf:
/opt/local/share/qt4/mkspecs/features/release.prf:
/opt/local/share/qt4/mkspecs/features/default_post.prf:
/opt/local/share/qt4/mkspecs/features/mac/default_post.prf:
/opt/local/share/qt4/mkspecs/features/mac/x86_64.prf:
/opt/local/share/qt4/mkspecs/features/mac/objective_c.prf:
/opt/local/share/qt4/mkspecs/features/warn_on.prf:
/opt/local/share/qt4/mkspecs/features/qt.prf:
/opt/local/share/qt4/mkspecs/features/unix/thread.prf:
/opt/local/share/qt4/mkspecs/features/moc.prf:
/opt/local/share/qt4/mkspecs/features/mac/rez.prf:
/opt/local/share/qt4/mkspecs/features/mac/sdk.prf:
/opt/local/share/qt4/mkspecs/features/resources.prf:
/opt/local/share/qt4/mkspecs/features/uic.prf:
/opt/local/share/qt4/mkspecs/features/yacc.prf:
/opt/local/share/qt4/mkspecs/features/lex.prf:
/opt/local/share/qt4/mkspecs/features/include_source_dir.prf:
/opt/local/lib/libQtGui.prl:
/opt/local/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile mdieditor.pro

mdieditor.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) mdieditor.app/Contents || $(MKDIR) mdieditor.app/Contents 
	@$(DEL_FILE) mdieditor.app/Contents/PkgInfo
	@echo "APPL????" >mdieditor.app/Contents/PkgInfo
mdieditor.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) mdieditor.app/Contents/Resources || $(MKDIR) mdieditor.app/Contents/Resources 
	@touch mdieditor.app/Contents/Resources/empty.lproj
	
mdieditor.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) mdieditor.app/Contents || $(MKDIR) mdieditor.app/Contents 
	@$(DEL_FILE) mdieditor.app/Contents/Info.plist
	@sed -e "s,@ICON@,icon.icns,g" -e "s,@EXECUTABLE@,mdieditor,g" -e "s,@TYPEINFO@,????,g" /opt/local/share/qt4/mkspecs/macx-g++/Info.plist.app >mdieditor.app/Contents/Info.plist
mdieditor.app/Contents/Resources/icon.icns: images/icon.icns
	@$(CHK_DIR_EXISTS) mdieditor.app/Contents/Resources/ || $(MKDIR) mdieditor.app/Contents/Resources/ 
	@$(DEL_FILE) mdieditor.app/Contents/Resources/icon.icns
	@$(COPY_FILE) images/icon.icns mdieditor.app/Contents/Resources/icon.icns
dist: 
	@$(CHK_DIR_EXISTS) .tmp/mdieditor1.0.0 || $(MKDIR) .tmp/mdieditor1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/mdieditor1.0.0/ && $(COPY_FILE) --parents editor.h mainwindow.h tileview.h .tmp/mdieditor1.0.0/ && $(COPY_FILE) --parents mdieditor.qrc .tmp/mdieditor1.0.0/ && $(COPY_FILE) --parents editor.cpp main.cpp mainwindow.cpp tileview.cpp .tmp/mdieditor1.0.0/ && (cd `dirname .tmp/mdieditor1.0.0` && $(TAR) mdieditor1.0.0.tar mdieditor1.0.0 && $(COMPRESS) mdieditor1.0.0.tar) && $(MOVE) `dirname .tmp/mdieditor1.0.0`/mdieditor1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/mdieditor1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r mdieditor.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_editor.cpp moc_mainwindow.cpp moc_tileview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_editor.cpp moc_mainwindow.cpp moc_tileview.cpp
moc_editor.cpp: editor.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ editor.h -o moc_editor.cpp

moc_mainwindow.cpp: mainwindow.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.h -o moc_mainwindow.cpp

moc_tileview.cpp: tileview.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ tileview.h -o moc_tileview.cpp

compiler_rcc_make_all: qrc_mdieditor.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_mdieditor.cpp
qrc_mdieditor.cpp: mdieditor.qrc \
		images/new.png \
		images/document.png \
		images/copy.png \
		images/cut.png \
		images/icon.png \
		images/save.png \
		images/paste.png \
		images/open.png
	/opt/local/bin/rcc -name mdieditor mdieditor.qrc -o qrc_mdieditor.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

editor.o: editor.cpp editor.h \
		globals.h \
		tileview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editor.o editor.cpp

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp editor.h \
		mainwindow.h \
		globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

tileview.o: tileview.cpp tileview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tileview.o tileview.cpp

moc_editor.o: moc_editor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editor.o moc_editor.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_tileview.o: moc_tileview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tileview.o moc_tileview.cpp

qrc_mdieditor.o: qrc_mdieditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_mdieditor.o qrc_mdieditor.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

